"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from .base import *
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8gkph6_vl!-zv$@yhqr5^=#oq8kn!64^ifj4#(47ve#(3n1p(c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition


# https://docs.djangoproject.com/zh-hans/3.2/ref/settings/
# mysql配置
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mysite_db',
        'USER': 'lxl',
        'PASSWORD': 'lxl123456',
        'HOST': 'localhost',
        'PORT': '3306',
    }}




# 发送邮件设置
# https://docs.djangoproject.com/en/2.0/ref/settings/#email
# https://docs.djangoproject.com/en/2.0/topics/email/
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # 默认使用的邮箱配置
EMAIL_HOST = 'smtp.qq.com'   # qq邮箱是通过这个域名发送
EMAIL_PORT = 25    # 发送邮箱端口
EMAIL_HOST_USER = '2972352405@qq.com'   # 邮箱地址
EMAIL_HOST_PASSWORD = 'aaqjhlfhackuddch'  # 授权码
EMAIL_SUBJECT_PREFIX = '[李小龙的博客] '
EMAIL_USE_TLS = True  # 与SMTP服务器通信时，是否启动TLS链接(安全链接)